name: Nightly Build

on:
  schedule:
  # Every night at 04:00 (UTC)
  - cron: '0 4 * * *'
  workflow_dispatch:
    inputs:
      release_branch:
        description: Branch to release
        required: true
        default: master
        type: string
      quay_org:
        description: Quay organization
        type: string
        default: kiali
        required: true

jobs:
  initialize:
    name: Initialize
    runs-on: ubuntu-20.04
    outputs:
      target_branch: ${{ github.ref_name }}
      quay_tag: ${{ env.quay_tag }}
      quay_org: ${{ env.quay_org }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.release_branch || github.ref_name }}

    - name: Determine Quay tag
      id: quay_tag
      run: |
        if [ -z ${{ github.event.inputs.quay_org }} ];
        then
          QUAY_ORG="kiali"
        else
          QUAY_ORG="${{ github.event.inputs.quay_org }}"
        fi

        QUAY_REPO="quay.io/$QUAY_ORG/kiali"
        QUAY_TAG="$QUAY_REPO:latest"
        
        echo "quay_tag=$QUAY_TAG" >> $GITHUB_ENV
        echo "quay_org=$QUAY_ORG" >> $GITHUB_ENV

    - name: Log information
      run: |
        echo "Release type: latest"

        echo "Quay tag": ${{ env.quay_tag }}
        echo "Quay org": ${{ env.quay_org }}

  build_backend:
    name: Build backend
    uses: ./.github/workflows/build-backend.yml
    needs: [initialize]
    with:
      build_branch: ${{ github.event.inputs.release_branch || github.ref_name }}

  build_frontend:
    name: Build frontend
    uses: ./.github/workflows/build-frontend.yml
    needs: [initialize]
    with:
      target_branch: ${{needs.initialize.outputs.target_branch}}
      build_branch: ${{ github.event.inputs.release_branch || github.ref_name }}

  push:
    name: Push latest
    # Avoid schedule workflows from forks to push images
    if: ${{ (github.event_name == 'schedule' && github.repository == 'kiali/kiali') || github.event_name != 'schedule' }}
    runs-on: ubuntu-20.04
    needs: [initialize, build_backend, build_frontend]
    env:
      QUAY_TAG: ${{ needs.initialize.outputs.quay_tag }}
      IMAGE_ORG: ${{ needs.initialize.outputs.quay_org }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.release_branch || github.ref_name }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
        # The builtin cache feature ensures that installing golangci-lint
        # is consistently fast.
        cache: true
        cache-dependency-path: go.sum

    - name: Download frontend build
      uses: actions/download-artifact@v3
      with:
        name: build
        path: frontend/build

    - name: Build and push image
      run: |
        docker login -u ${{ secrets.QUAY_USER }} -p ${{ secrets.QUAY_PASSWORD }} quay.io

        make -e DOCKER_CLI_EXPERIMENTAL=enabled build-linux-multi-arch container-multi-arch-all-push-kiali-quay

  push_test_images:
    name: Build and push tests images
    uses: ./.github/workflows/tests-images-creator.yml
    needs: [initialize, build_backend, build_frontend]
    with:
      release_branch: ${{ github.event.inputs.release_branch || github.ref_name }}
      images_tag: latest
      quay_org: ${{ needs.initialize.outputs.quay_org }}
    secrets:
      QUAY_USER: ${{ secrets.QUAY_USER }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
